"""Shared protocol definitions for entrypoint runtime adapters."""

from __future__ import annotations

from typing import TYPE_CHECKING, Awaitable, Callable, Protocol

from archive_catalog import CollectionInfo
from domain_state import PlaylistState

if TYPE_CHECKING:
    from aiohttp import ClientSession


class ArchiveRuntimeProtocol(Protocol):
    def parse_sap_header(self, filepath: str) -> dict[str, str]: ...
    def load_metadata_cache(self) -> dict[str, dict[str, str]]: ...
    def save_metadata_cache(self, index: dict[str, dict[str, str]]) -> None: ...
    async def fetch_metadata_batch(
        self,
        session: ClientSession,
        urls: list[str],
        *,
        batch_size: int = 20,
    ) -> dict[str, dict[str, str]]: ...
    def search_tracks(self, query: str, tracks: list[str], *, limit: int = 10) -> list[str]: ...
    async def refresh_tracklist(self) -> list[str]: ...
    def load_cached_tracklist(self) -> list[str] | None: ...
    def parse_songlengths_to_tracks(self, data: str) -> list[str]: ...
    def download_hvsc_index(self) -> list[str] | None: ...
    def load_cached_hvsc(self) -> list[str] | None: ...
    def load_modarchive_cache(self) -> list[str] | None: ...
    def load_ay_cache(self) -> list[str] | None: ...
    def load_ym_cache(self) -> list[str] | None: ...
    def load_tiny_cache(self) -> list[str] | None: ...
    def load_asma_local_cache(self) -> list[str] | None: ...
    def load_hvsc_local_cache(self) -> list[str] | None: ...
    def load_snes_cache(self) -> list[str] | None: ...
    async def download_spc_rsn(self, rsn_url: str, spc_now: str, game_name: str) -> str | None: ...
    async def download_modarchive_module(self, url: str, retries: int = 2) -> str: ...
    def parse_sid_header(self, data: bytes) -> dict[str, str]: ...
    def cleanup_orphan_players(self) -> None: ...


class PlaybackAssetsProtocol(Protocol):
    def ym_to_wav(self, ym_path: str) -> str: ...
    def ym_cleanup(self) -> None: ...
    def resolve_local_path(self, url: str) -> str | None: ...
    async def download_sap(self, url: str, retries: int = 2) -> str: ...
    def set_ym_last_wav_path(self, path: str | None) -> None: ...


class CollectionRuntimeProtocol(Protocol):
    def get_collection_info(self, mode: str) -> CollectionInfo: ...
    async def load_tracks_for_mode(self, mode: str) -> list[str] | None: ...
    async def ensure_tracks(self, state: PlaylistState) -> bool: ...
    async def switch_collection(
        self,
        ctx: object,
        mode: str,
        *,
        flip_seq: list[str] | None = None,
    ) -> bool: ...
    def get_cache_count(self, fname: str) -> int | str: ...
    def get_all_cache_counts(self, cache_map: dict[str, tuple[str, str]]) -> dict[str, tuple[str, int | str]]: ...


class PlaybackRuntimeProtocol(Protocol):
    async def pre_download_next(self, state: PlaylistState) -> None: ...
    async def start_targeted_playback_session(self, ctx: object, state: PlaylistState, url: str) -> bool: ...
    async def play_current_track(self, ctx: object) -> bool: ...
    async def skip_to_next(self, ctx: object) -> None: ...
    async def auto_play_after_switch(self, ctx: object, state: PlaylistState) -> None: ...
    async def fetch_metadata_background(self) -> None: ...


class SubsongRuntimeProtocol(Protocol):
    def get_subsongs(self, filepath: str) -> list[float]: ...
    def has_subsongs(self, filepath: str) -> bool: ...
    def convert_subsong(self, filepath: str, subsong: int, output_path: str) -> bool: ...
    def subsong_temp_path(self, filepath: str, subsong: int) -> str: ...
    async def play_subsong(
        self,
        ctx: object,
        state: PlaylistState,
        subsong: int,
        *,
        audacious_stop: Callable[[], None],
        audacious_play: Callable[[str], None],
        setup_monitor_source: Callable[[object], None],
    ) -> bool: ...
    def cleanup_subsong_temp_wavs(self, state: PlaylistState) -> None: ...


class PlaySubsongCallable(Protocol):
    async def __call__(
        self,
        ctx: object,
        state: PlaylistState,
        subsong: int,
        *,
        audacious_stop: Callable[[], None],
        audacious_play: Callable[[str], None],
        setup_monitor_source: Callable[[object], None],
    ) -> bool: ...


class ServiceFacadeProtocol(CollectionRuntimeProtocol, PlaybackRuntimeProtocol, Protocol):
    def bind(
        self,
        *,
        collection_service: CollectionRuntimeProtocol,
        playback_service: PlaybackRuntimeProtocol,
    ) -> None: ...

    def filter_blacklisted(self, tracks: list[str], user_id: int | str) -> list[str]: ...
    def get_subsongs(self, filepath: str) -> list[float]: ...
    def has_subsongs(self, filepath: str) -> bool: ...
    def convert_subsong(self, filepath: str, subsong: int, output_path: str) -> bool: ...
    def subsong_temp_path(self, filepath: str, subsong: int) -> str: ...
    async def play_subsong(
        self,
        ctx: object,
        state: PlaylistState,
        subsong: int,
        *,
        audacious_stop: Callable[[], None],
        audacious_play: Callable[[str], None],
        setup_monitor_source: Callable[[object], None],
    ) -> bool: ...
    def cleanup_subsong_temp_wavs(self, state: PlaylistState) -> None: ...
    def stop_all_players(self, cleanup_subsong_temp_wavs: Callable[[PlaylistState], None]) -> None: ...


class StreamRuntimeProtocol(Protocol):
    def setup_monitor_source(self, source: object) -> None: ...
    async def stop_state_streams(self, state: PlaylistState) -> None: ...
